//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CourseManagerEntities : DbContext
    {
        public CourseManagerEntities()
            : base("name=CourseManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
           
        }
    
        public DbSet<Teachers> Teachers { get; set; }
        public DbSet<Classe> Classe { get; set; }
        public DbSet<Students> Students { get; set; }
        public DbSet<CourseManagemants> CourseManagemants { get; set; }
        public DbSet<course> course { get; set; }
    }
}
